apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      type: frontend
      deployment: blue
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: frontend
        deployment: blue
    spec:
      containers:
        - name: frontend
          image: mstar228/techup-frontend:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d/
            - name: tls-config
              mountPath: /etc/nginx/ssl/
      volumes:
        - name: config
          configMap:
            name: frontend-conf
        - name: tls-config
          secret:
            secretName: tls-secret
